language: node_js
node_js:
  - node

cache: npm

script:
  - npm install codecov -g
  - npm install
  - npm run ci-test
  - npm run report-coverage

after_success:
  - .\node_modules\.bin\nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)